### ISSUE TITLE
OpenSSL for OSX

### ISSUE THREAD

**Issue by wuaschtikus** [x2on/OpenSSL-for-iPhone#100]
Hi!

It is possible to add OSX Architectures to your build-libssl script?
When trying to build with a sperate OSX Build Target in my project results in several warnings:

`ld: warning: URGENT: building for OSX, but linking in object file (/Volumes/***/openssl-ios/Core/lib/libcrypto.a(bio_lib.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (/Volumes/***/openssl-ios/Core/lib/libcrypto.a(bss_mem.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (/Volumes/***/openssl-ios/Core/lib/libcrypto.a(err_all.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (/Volumes/***/openssl-ios/Core/lib/libcrypto.a(err_prn.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (/Volumes/***/openssl-ios/Core/lib/libcrypto.a(p_lib.o)) built for iOS. Note: This will be an error in the future.`

and so on...

Appreciate your work here since it is really hard to find a script like this which works convenient!

Cheers!

**Comment by x2on** [comment]
You could use the normal build scripts for OS X. No need for using special project like this.
