### ISSUE TITLE
Dynamic framework missing bitcode

### ISSUE THREAD

**Issue by BlueVirusX** [x2on/OpenSSL-for-iPhone#101]
Hi,

I ran into an issue when I tried to include the OpenSSL library as a dynamic framework instead of a static one.

When I use "./create-openssl-framework.sh **dynamic**" to create the dynamic framework and try to build my project which depends on OpenSSL then I get the error that **bitcode is missing for architecture arm7**.

But when I use "./create-openssl-framework.sh" and build my project with the static OpenSSL library it builds without any problems.

I'm using Xcode 7.3.1 and my project supports iOS 8+

**Comment by x2on** [comment]
Feel free to submit a PR - i do not use dynamic frameworks at all.

**Comment by x2on** [comment]
Ok `otool -arch armv7 -l lib/libssl.a | grep bitcode` shows that the library contains bitcode.
After creating the dynamic framework the bitcode part is gone.

**Comment by x2on** [comment]
That happens for all architectures not only for armv7.

Currently we are using the following command for generating the dynamic framwork:
```bash
libtool -no_warning_for_no_symbols -dynamic -undefined dynamic_lookup -ios_version_min 8.0 -o openssl.framework/openssl lib/libcrypto.a lib/libssl.a
```

**Comment by vixentael** [comment]
Hi @x2on 

What is the latest status of this issue? Have you managed to generate dynamic framework that includes bitcode?

**Comment by keeshux** [comment]
While I understand that the issue was closed for inactivity, the problem persists. Using Xcode 9.

**Comment by aelam** [comment]
@x2on  currently the build script has config options `no-shared`.  so there is no dynamic libraries output  maybe combine the shared libraries output could solve this?
