### ISSUE TITLE
ld Library not found for dynamic framework

### ISSUE THREAD

**Issue by jcavar** [x2on/OpenSSL-for-iPhone#103]
We had some issues integrating dynamic framework even in sample application provided in this project. 
So the problem was that path was not correct inside openssl binary.

We solved this by running:
`install_name_tool -id "@executable_path/Frameworks/openssl.framework/openssl" openssl.framework/openssl`

You can see more about this here:
http://stackoverflow.com/questions/5522126/dyld-not-able-to-load-dylibs

I don't understand problem well enough to make a pull request, but it maybe makes sense  to add `install_name_tool` step in shell script.

btw. Were you able to integrate this without making any changes?

**Comment by x2on** [comment]
Hi,

interesting problem - but i would not add this until knowing what install_name_tool does and what implications it have for the build process.

**Comment by keeshux** [comment]
I can definitely confirm lookup issues with the dynamic framework. In fact `install_name_tool` is not needed, providing `-install_name` to `libtool` worked for me. I'm still facing an issue on iOS 9, so more details later.

Anyway, the overall feedback so far is that the dynamic version of the framework is not working properly out-of-the-box.

**Comment by keeshux** [comment]
Details in #158.
