### ISSUE TITLE
missing required architecture x86_64 in file

### ISSUE THREAD

**Issue by MontassarWCT** [x2on/OpenSSL-for-iPhone#106]
I have a sample application ios and i tried to integrated min static Lib libSonicProxyLibrary.a.
but i have 4 errors, and i can't bluid  my app.

`
ld: warning: ignoring file /Users/montassarzarroug/Documents/projects/CopSonic SDK/20160728-01 SonicProxy Android-iOS/20160728-01 SonicProxy Android-iOS/iOS/SonicProxyUseSample_Swift_V2/External/lib/libSonicProxyLibrary.a, missing required architecture x86_64 in file /Users/montassarzarroug/Documents/projects/CopSonic SDK/20160728-01 SonicProxy Android-iOS/20160728-01 SonicProxy Android-iOS/iOS/SonicProxyUseSample_Swift_V2/External/lib/libSonicProxyLibrary.a (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SPClientManager", referenced from:
      type metadata accessor for __ObjC.SPClientManager in SonicProxyURLProtocol.o
      type metadata accessor for __ObjC.SPClientManager in SonicProxyClientManagerExtension.o
      l__CATEGORY_SPClientManager_$_SonicProxyUseSample in SonicProxyClientManagerExtension.o
  "_OBJC_CLASS_$_SPHostManager", referenced from:
      type metadata accessor for __ObjC.SPHostManager in SonicHostVC.o
  "_OBJC_CLASS_$_SPRequest", referenced from:
      type metadata accessor for __ObjC.SPRequest in SonicProxyClientManagerExtension.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

And in Setting architectures, i have $(ARCHS_STANDARD),armv7, armv7s, arm64
Please, someone can help me ??

**Comment by x2on** [comment]
Hi,

sorry but you are missing `x86_64` in the library `libSonicProxyLibrary.a` not in the OpenSSL-for-iPhone project. So get a `x86_64` compatible library.
