### ISSUE TITLE
Only build subset of archs

### ISSUE THREAD

**Issue by jberkel** [x2on/OpenSSL-for-iPhone#109]
Would be great if a flag could be passed to `build-libssl.sh` to only build certain archs – my project for example does not need armv7s / tvOS.

Right now I use a fork but would ideally not have the maintenance overhead.

**Comment by oneton** [comment]
I have created a version of the script for use with OpenSSL 1.1.0 (see my fork). I still intend to create a couple of pull requests for my changes (which are both related to the script process itself as well as the specifics for OpenSSL 1.1.0). One of those changes includes selectable targets (although it'll probably be a variable in the script file).

I cannot promise any timeframe though, my schedule is packed at the moment.

**Comment by jberkel** [comment]
yes, it would just need a way to pass in variables to the script, that's quite easy with conditional assignments, along the lines of

`: ${archs:="i386 arm64"}`

Then some logic to conditionally include the lips in the lipo step. There isn't really much more to it.

**Comment by x2on** [comment]
Fixed by #111
