### ISSUE TITLE
Can't compile it

### ISSUE THREAD

**Issue by cippyboy** [x2on/OpenSSL-for-iPhone#123]
After running build-libssl.h in the terminal, I still get "please run ./build-libssl.h".

Why do I even need to run shell scripts anyway ? I just need an xcodeproject with all the compilation units and all include directories set up.

**Comment by x2on** [comment]
Please check the logfiles in the `bin` folder.

**Comment by cippyboy** [comment]
Already deleted this library. If I have to scan log files in order to compile a solution file that you already have on your computer, this is a failed project. I'm using polarssl now. I just dragged the source files into my project and it worked, thank goodness !

**Comment by x2on** [comment]
There is no OpenSSL for iOS on your computer - so if you need to use it you have to compile it.

PolarSSL is an alternative, but it has different use cases and apis then OpenSSL.

This is not the OpenSSL project, this is just a script to compile it.

**Comment by cippyboy** [comment]
It seems you don't understand the issue here. 
Quote : "this is just a script to compile it"
This is the problem. I don't want a script to compile it. I want an .xcodeproj to compile it and nothing else. There is an .xcodeproj in the repository but it doesn't work.

**Comment by x2on** [comment]
OpenSSL is a widly used library for encryption. It has no standard support for iOS projects.
OpenSSL is not a Xcode project - so it isn't possible to build it with an .xcodeproj.
This project provides a script for building a library from the source, so you could use it with any .xcodeproj.

If you don't wan't that you can use OpenSSL.

So i understand your comment, but it's not possible with OpenSSL.

**Comment by cippyboy** [comment]
1. Why is this repository named OpenSSL for iPhone then ?
2. Why is there an xcodeproj in this repository ?
3. How do you compile a project for iPhone without Xcode ? I don't think this obeys Apple's policies and I'm afraid any app would be rejected if it's not compiled with Xcode.

**Comment by x2on** [comment]
1. Because this projects compiles OpenSSL for iOS (iPhone)
2. Because it contains an example project (see README.md)
3. It compiles with bundled command line tools from Xcode to a static library (libssl.a) which is a Apple standard and allowed.

**Comment by h3smith** [comment]
If you think an open source project lacks functionality, branch it and add what you need. There is no need to be abusive towards maintainers who started the project because it lacks some specific functionality you desire. Open source doesn't mean "you work for me."

**Comment by cippyboy** [comment]
Specific functionality ? You should replace that with "basic" functionality. In order to build an iPhone app you need to use Xcode. Why complicate things and make it compilable from command line only ? If I wanted to give you a library, you can bet I'd give you the project file instead of telling you how to configure a build system that can fail at every step. I mean seriously, when you download an Apple or Microsoft sample project, do you ever build it with a command line tool ? Sure you can do that. But why complicate life and make compilation a lengthy and painful process ?

**Comment by x2on** [comment]
Because there are laws which says it is illegal to provide compiled crypto libraries.
And OpenSSL could not be build without command line at all!
If you like to use cryptography with Xcode without command line use Apple's built in crypto library!

Im going to close this discussion now!
