### ISSUE TITLE
cannot read private RSA BIO with PEM_read_bio_RSAPrivateKey()!

### ISSUE THREAD

**Issue by suniliphone** [x2on/OpenSSL-for-iPhone#124]
![screen shot 2016-10-21 at 11 09 43 am](https://cloud.githubusercontent.com/assets/6223169/19587951/f7ddec34-977f-11e6-96e4-11a4fc46fb0a.png)

i have used following method for generating private key and using that value in "CTOpenSSLRSASignWithPrivateKey" .

While executing i am getting following error.

 NSData *privateKeyData = CTOpenSSLGeneratePrivateRSAKey(1024,CTOpenSSLPrivateKeyFormatDER);

**Comment by x2on** [comment]
Please ask on the OpenSSL project - this is just the build environment for OpenSSL on iOS, not OpenSSL problems itseld.
