### ISSUE TITLE
The scripts beaks for openssl 1.1.0.b. Any chance of fixing it?

### ISSUE THREAD

**Issue by ogoren** [x2on/OpenSSL-for-iPhone#125]
It fails pretty much near the lipo commands, when it cannot found to output to combine. It works fine for 1.0.2.g, for example/

**Comment by oneton** [comment]
The build process for OpenSSL 1.1 has undergone major changes from 1.0.2. As a result, the script doesn't work for 1.1.0 yet. The --help output clearly states that is does not work with 1.1.0 yet. I have a pull request ready which does include the 1.1.0 build. You could try that. https://github.com/x2on/OpenSSL-for-iPhone/pull/120

**Comment by x2on** [comment]
Fixed with #128
