### ISSUE TITLE
add support for macOS?

### ISSUE THREAD

**Issue by langyanduan** [x2on/OpenSSL-for-iPhone#132]
it seems no build option for macOS, can you add macOS arch ? thank you

**Comment by wuaschtikus** [comment]
Yes please this would be very nice!

**Comment by x2on** [comment]
OpenSSL is already integrated in macOS, so there is no need to build it.
You could also easily build it with the original sources (see https://wiki.openssl.org/index.php/Compilation_and_Installation)
