### ISSUE TITLE
Your path contains whitespaces, which is not supported by 'make install'.

### ISSUE THREAD

**Issue by kynwu** [x2on/OpenSSL-for-iPhone#133]
I got this msg when running `./build-libssl.sh --version=1.1.0c`.
and I did some research but still have no solutions. 
What does this error msg mean? Is that my $PATH contains whitespace or ?

I'm looking forward to some suggestions. Thanks if anyone could probably help me out of this!

**Comment by x2on** [comment]
That means the folder of your local copy of this project contains an whitespace. Remove that whitespace from the folder name and it works fine.

**Comment by kynwu** [comment]
Thanks for reply! After checking, it turns out that I had clone the repo. into a symbolic link of another folder. Not so obvious for me to notice such mistake. Thanks anyway!
