### ISSUE TITLE
Beginners Question: Once the project is built, how to add it to own project?

### ISSUE THREAD

**Issue by RyanHop3** [x2on/OpenSSL-for-iPhone#136]
Hi, sorry if this is a stupid question but I am new to programming and wondering what the next step is after I have built the project using `./build-libssl.sh --version=1.1.0d` in order to incoperate openssl into my own project.

Thanks, Ryan.

**Comment by x2on** [comment]
You have to add the libraries and the headers to your project.
(http://stackoverflow.com/questions/2093069/xcode-how-to-include-c-library-and-header-file-to-cocoa-project)
