### ISSUE TITLE
some methods are missed

### ISSUE THREAD

**Issue by AlterX76** [x2on/OpenSSL-for-iPhone#139]
Hi I have compiled openssl 1.1.0d using your script for ios armv7 when I use it in my static lib it is complaining (undeclared identifiers) about few methods like:
   OpenSSL_add_all_algorithms();
    SSL_load_error_strings();   
    method = (SSL_METHOD*)TLSv1_2_client_method()
SSL_library_init()

Do you have a clue about this?
I am using the same code and same headers for android or windows and linux without problems

Thanks

**Comment by x2on** [comment]
Do you have setup your project correct, included the headers and the library files?

**Comment by x2on** [comment]
Im going to close this issue - feel free to reopen if you still need help.
