### ISSUE TITLE
Size of libcrypto.a

### ISSUE THREAD

**Issue by kragekjaer** [x2on/OpenSSL-for-iPhone#147]
Hi,

I have noticed the size of libcrypto.a is 38 mb.
Can someone point out where to configure the build if e.g I dont want to use EC

E.g set

no-idea       -DOPENSSL_NO_IDEA
no-aes        -DOPENSSL_NO_AES
no-camellia   -DOPENSSL_NO_CAMELLIA
no-seed       -DOPENSSL_NO_SEED
no-bf         -DOPENSSL_NO_BF
no-cast       -DOPENSSL_NO_CAST
no-des        -DOPENSSL_NO_DES
no-rc2        -DOPENSSL_NO_RC2
no-rc4        -DOPENSSL_NO_RC4
no-rc5        -DOPENSSL_NO_RC5

no-md2        -DOPENSSL_NO_MD2
no-md4        -DOPENSSL_NO_MD4
no-md5        -DOPENSSL_NO_MD5
no-sha        -DOPENSSL_NO_SHA
no-ripemd     -DOPENSSL_NO_RIPEMD
no-mdc2       -DOPENSSL_NO_MDC2

no-rsa        -DOPENSSL_NO_RSA
no-dsa        -DOPENSSL_NO_DSA
no-dh         -DOPENSSL_NO_DH

no-ec         -DOPENSSL_NO_EC
no-ecdsa      -DOPENSSL_NO_ECDSA
no-ecdh       -DOPENSSL_NO_ECDH

**Comment by oneton** [comment]
See also the script's help output:
```oneton-mbp:OpenSSL-for-iPhone oneton$ ./build-libssl.sh -h
Usage: ./build-libssl.sh [options...]
(...)

For custom configure options, set variable CONFIG_OPTIONS
For custom cURL options, set variable CURL_OPTIONS
  Example: CURL_OPTIONS="--proxy 192.168.1.1:8080" ./build-libssl.sh
```

So, since the options you mention are configure options, try
```
CONFIG_OPTIONS="no-ec" ./build-libssl.sh
```

**Comment by kragekjaer** [comment]
Thank you very much
