### ISSUE TITLE
How to use openssl in private pod?

### ISSUE THREAD

**Issue by SanyasiraoM** [x2on/OpenSSL-for-iPhone#154]
Hi @x2on,

I followed
https://stackoverflow.com/a/41856095/5059959
http://x2on.de/2010/02/01/tutorial-iphone-app-with-compiled-openssl-library/  to use openssl to generate pkcs12 file.

Now we need to create a private pod which requires openssl. How to can I do that?

Could you help me

**Comment by x2on** [comment]
I think this is more a question about the usage of CocoaPods.
