### ISSUE TITLE
Some methods are undeclared

### ISSUE THREAD

**Issue by prohith001** [x2on/OpenSSL-for-iPhone#156]
Hi I have compiled openssl 1.1.0f using your script for ios arm64 when I use it in my static lib it is complaining (undeclared identifiers) about few methods like:
OpenSSL_add_all_algorithms();
SSL_load_error_strings();
method = (SSL_METHOD*)TLSv1_2_client_method()
SSL_library_init()

Do you have a clue about this?
I am using the same code and same headers for android or windows and linux without problems

Thanks

**Comment by x2on** [comment]
Where are this methods defined? Did you import the correct headers?
