### ISSUE TITLE
Dynamic framework is unusable for several reasons

### ISSUE THREAD

**Issue by keeshux** [x2on/OpenSSL-for-iPhone#158]
1) The library `install_name` is not relative to `@rpath` and therefore leads to lookup issues at runtime ("Image not found").

2) It's not dynamically linked to `System` (which basically includes the C library), leading to crashes on my iOS 9 devices. This is erroneously suppressed by the `-undefined dynamic_lookup` as described in http://www.openradar.me/23140620

3) The bundled `Info.plist` is not suitable for use of the framework outside of Xcode, because it has $ variables. When bundled as-is, `codesign` is tricked into signing the `Info.plist` file instead of the binary.

After manually addressing the 3 issues, my apps are working properly.

FWIW, I'll be happy to draft a PR soon with the above issues fixed directly in the scripts.

**Comment by h3smith** [comment]
One issue I had with libssl and libcrypto with iOS 11 and dylibs- iOS 11 now includes BoringSSL. So if your rpaths aren’t set right in the dylibs you’ll get weird results.

**Comment by keeshux** [comment]
Yeah `install_name` is a very annoying Apple .. flaw? I believe that `@rpath/openssl.framework/openssl` suits most use-cases though.

**Comment by keeshux** [comment]
@h3smith please don't pollute the issue thread, your comments are way off topic.

**Comment by nawaf4** [comment]
acces
