### ISSUE TITLE
When trying to run "make depend" with CONFIG_OPTIONS set , it always throws an error for armv7 and armv7s

### ISSUE THREAD

**Issue by LiberAC** [x2on/OpenSSL-for-iPhone#160]
Hi.

I'm trying to run the script and I'm setting the CONFIG_OPTIONS with the following: "-no-seed -no-bf -no-cast -no-rc2 -no-rc4 -no-md4 -no-camellia -no-ripemd -no-mdc2 -no-dsa -no-dh -no-err -no-engine -no-hw -no-capieng"

It's all good for arm64, however when it runs for armv7 and armv7s, it throws the error

>  "  Make depend...making depend in crypto...
> clang: error: optimization flag '-fomit-frame-pointer' is not supported for target 'armv7' [-Werror,-Wignored-optimization-argument]
> make[1]: *** [local_depend] Error 1
> make: *** [depend] Error 1"

I see that when you DO NOT set the CONFIG_OPTIONS it throws a WARNING but not an error about the "-fomit-frame-pointer'

Do you have any pointer on how solve this, it's important to me to have the binaries as slim as possible.

[logARMV7.txt](https://github.com/x2on/OpenSSL-for-iPhone/files/1633012/logARMV7.txt)

**Comment by x2on** [comment]
If you explicit set the config option it will fail, because it's not supported on armv7
