### ISSUE TITLE
i386 builds, max supported mios-version-min needs to be set to 10

### ISSUE THREAD

**Issue by gaming-hacker** [x2on/OpenSSL-for-iPhone#164]
Cool script.  Especially the nice little old school spinner.

I was building only for iOS 11.0 and did not want to support anything earlier but during i386 build if fails with error

```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk -fno-common -fembed-bitcode -mios-version-min=11.0  -fPIC -c -o crypto/aes/aes-586.o crypto/aes/aes-586.s
clang: error: invalid iOS deployment version '-miphoneos-version-min=11.0', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]
```

I have my own separate build script for frameworks and got the same error and wanted to validate the error so I just put in a quick and dirty [[ ]] &&

**Comment by x2on** [comment]
iOS 11 is 64-Bit only
