### ISSUE TITLE
Compilation failed in version 1.1.1a

### ISSUE THREAD

**Issue by muzipiao** [x2on/OpenSSL-for-iPhone#171]
Compilation failed in version 1.1.1a, can you update the script, thank you very much.

**Comment by coffey** [comment]
default Xcode Developer path /Library/Developer/CommandLineTools is exist，so the script use this path to build, but Toolchains is not exist in it.
use "xcode-select -switch /Applications/Xcode.app/Contents/Developer" to reset default Developer path can solve this problem。

**Comment by coffey** [comment]
> Compilation failed in version 1.1.1a, can you update the script, thank you very much.

default Xcode Developer path /Library/Developer/CommandLineTools is exist，so the script use this path to build, but Toolchains is not exist in it.
use "xcode-select -switch /Applications/Xcode.app/Contents/Developer" to reset default Developer path can solve this problem。
