### ISSUE TITLE
How to support new arch 'arm64e'

### ISSUE THREAD

**Issue by kinglezhuang** [x2on/OpenSSL-for-iPhone#172]
Currently, iPhone XS/XS Max/XR support new arch 'arm64e', we want to the script can build such arch. 

But i don't know how to modify 'DEFAULTTARGETS="ios-sim-cross-x86_64 ios-sim-cross-i386 ios64-cross-arm64 ios-cross-armv7s ios-cross-armv7 tvos-sim-cross-x86_64 tvos64-cross-arm64" ' & '      *_ios_arm64.h)
        DEFINE_CONDITION="TARGET_OS_IOS && TARGET_OS_EMBEDDED && TARGET_CPU_ARM64"
      ;;'

**Comment by kinglezhuang** [comment]
https://github.com/jasonacox/Build-OpenSSL-cURL

Finally, I use above build script to support 1.1.1b & arm64e

**Comment by x2on** [comment]
https://github.com/openssl/openssl/issues/8745

**Comment by x2on** [comment]
Okay, looks like changing the arch from arm64 to arm64 works fine. ;)
