### ISSUE TITLE
[Catalyst]  Build for the Mac

### ISSUE THREAD

**Issue by chrisvanbuskirk** [x2on/OpenSSL-for-iPhone#175]
Feature request that it builds for Catalyst (UKitForMac).

**Comment by marcelosalloum** [comment]
I've just opened a PR supporting Catalyst @chrisvanbuskirk 

If you want to quickly test it you can just run:
```bash
git clone git@github.com:marcelosalloum/OpenSSL-for-iPhone.git --branch feature/mac-catalyst && \
cd OpenSSL-for-iPhone && \
./build-libssl.sh --archs="MacOSX_x86_64 i386 arm64 armv7s armv7"
```

BTW, you will need to be on MacOSX 10.15 and Xcode 11 for it to succeed.

**Comment by x2on** [comment]
Thanks for the PR - i merged it
