### ISSUE TITLE
Feature request: Better support for debug builds

### ISSUE THREAD

**Issue by mmartikainen** [x2on/OpenSSL-for-iPhone#178]
It would be useful to have a `--debug` flag that conveniently sets appropriate config options for debug builds (e.g. `no-asm -g3 -O0 -fno-omit-frame-pointer -fno-inline-functions`). 

With that flag set it would also be great to keep the `src` content around after the build, to make it simple to step into OpenSSL code when debugging in xcode.

**Comment by x2on** [comment]
You could add these flags easily with `CONFIG_OPTIONS` when calling `build-libssl.sh`
