### ISSUE TITLE
How do enable Mac Catalyst support?

### ISSUE THREAD

**Issue by PomegranateApps** [x2on/OpenSSL-for-iPhone#184]
When I try to compile for Mac Catalyst I'm getting these errors.

`Building for Mac Catalyst, but the linked library 'libssl.a' was built for iOS + iOS Simulator. You may need to restrict the platforms for which this library should be linked in the target editor, or replace it with an XCFramework that supports both platforms.`

**Comment by vgritsenko** [comment]
You can use XCFramework from https://github.com/x2on/OpenSSL-for-iPhone/pull/200
