### ISSUE TITLE
Error Unable to determine target or target not included in OpenSSL build when iOS <= 10.0

### ISSUE THREAD

**Issue by st400** [x2on/OpenSSL-for-iPhone#186]
I get the following error when i try to build a archive-build:

> Error Unable to determine target or target not included in OpenSSL build

If I set the iOS Deployment Target to iOS 11 or newer the build is successful. Is there a problem with opensslconf.h? I was also able to reproduce the problem with the example project.

**Comment by sandsuma** [comment]
I too see the error when I attach openssl.framework generated using create-openssl-framework.sh to my project. I was using 1.0.0.f before and never seen this problem. 
I tried on both xcode 10/11 device/simulator, tried changing deployment target  for the project to 11 and 12 , but no success

**Comment by st400** [comment]
I have not added the openssl.framework. 
Instead, I added the libraries libcrypto.a and libssl.a and the header files.

**Comment by zulfishah** [comment]
Did you find a solution for this? I'm running into the same Xcode error, even though my framework has a deployment target of iOS12

**Comment by vgritsenko** [comment]
I have not seen this issue when building for iOS 9 with this PR https://github.com/x2on/OpenSSL-for-iPhone/pull/200
