### ISSUE TITLE
Original tutorials are gone

### ISSUE THREAD

**Issue by thejeff77** [x2on/OpenSSL-for-iPhone#188]
Any chance someone copied the referenced tutorials (404)?

Would love to read them.

**Comment by mingvase** [comment]
@thejeff77 

https://x2on.github.io/2010/02/01/tutorial-iphone-app-with-compiled-openssl-library/
https://x2on.github.io/2010/07/13/tutorial-iphone-app-with-compiled-openssl-1-0-0a-library/
