### ISSUE TITLE
Build mac-catalyst failed with Xcode 11.4 (11E146)

### ISSUE THREAD

**Issue by csutanyu** [x2on/OpenSSL-for-iPhone#191]
I cd to OpenSSL-for-iPhone and build with command:
./build-libssl.sh --targets="mac-catalyst-x86_64" --disable-bitcode --version="1.1.1d"
then it will output error message:
![image](https://user-images.githubusercontent.com/1973092/78655529-b8732d80-78f8-11ea-8807-b8bfa4f45fcd.png)

**Comment by csutanyu** [comment]
The build-openssl-1.1.1d.log content is as following:

Configuring OpenSSL version 1.1.1d (0x1010104fL) for mac-catalyst-x86_64
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL file first)         ***
***                                                                ***
**********************************************************************
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" crypto/include/internal/bn_conf.h.in > crypto/include/internal/bn_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" crypto/include/internal/dso_conf.h.in > crypto/include/internal/dso_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
/Applications/Xcode.app/Contents/Developer/usr/bin/make depend && /Applications/Xcode.app/Contents/Developer/usr/bin/make _all
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I. -Iinclude -fPIC -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk -fno-common -mmacosx-version-min=10.15 -target x86_64-apple-ios13.0-macabi -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/ssl\"" -DENGINESDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DOPENSSL_API_COMPAT=0x10100000L  -MMD -MF apps/app_rand.d.tmp -MT apps/app_rand.o -c -o apps/app_rand.o apps/app_rand.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I. -Iinclude -fPIC -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk -fno-common -mmacosx-version-min=10.15 -target x86_64-apple-ios13.0-macabi -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/ssl\"" -DENGINESDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DOPENSSL_API_COMPAT=0x10100000L  -MMD -MF apps/apps.d.tmp -MT apps/apps.o -c -o apps/apps.o apps/apps.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I. -Iinclude -fPIC -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk -fno-common -mmacosx-version-min=10.15 -target x86_64-apple-ios13.0-macabi -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/ssl\"" -DENGINESDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DOPENSSL_API_COMPAT=0x10100000L  -MMD -MF apps/bf_prefix.d.tmp -MT apps/bf_prefix.o -c -o apps/bf_prefix.o apps/bf_prefix.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I. -Iinclude -fPIC -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk -fno-common -mmacosx-version-min=10.15 -target x86_64-apple-ios13.0-macabi -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/ssl\"" -DENGINESDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DOPENSSL_API_COMPAT=0x10100000L  -MMD -MF apps/opt.d.tmp -MT apps/opt.o -c -o apps/opt.o apps/opt.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I. -Iinclude -fPIC -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk -fno-common -mmacosx-version-min=10.15 -target x86_64-apple-ios13.0-macabi -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/ssl\"" -DENGINESDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DOPENSSL_API_COMPAT=0x10100000L  -MMD -MF apps/s_cb.d.tmp -MT apps/s_cb.o -c -o apps/s_cb.o apps/s_cb.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I. -Iinclude -fPIC -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk -fno-common -mmacosx-version-min=10.15 -target x86_64-apple-ios13.0-macabi -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/ssl\"" -DENGINESDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DOPENSSL_API_COMPAT=0x10100000L  -MMD -MF apps/s_socket.d.tmp -MT apps/s_socket.o -c -o apps/s_socket.o apps/s_socket.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I. -Icrypto/include -Iinclude -fPIC -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk -fno-common -mmacosx-version-min=10.15 -target x86_64-apple-ios13.0-macabi -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/ssl\"" -DENGINESDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DOPENSSL_API_COMPAT=0x10100000L  -MMD -MF crypto/aes/aes_cbc.d.tmp -MT crypto/aes/aes_cbc.o -c -o crypto/aes/aes_cbc.o crypto/aes/aes_cbc.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I. -Icrypto/include -Iinclude -fPIC -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk -fno-common -mmacosx-version-min=10.15 -target x86_64-apple-ios13.0-macabi -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/ssl\"" -DENGINESDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DOPENSSL_API_COMPAT=0x10100000L  -MMD -MF crypto/aes/aes_cfb.d.tmp -MT crypto/aes/aes_cfb.o -c -o crypto/aes/aes_cfb.o crypto/aes/aes_cfb.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I. -Icrypto/include -Iinclude -fPIC -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk -fno-common -mmacosx-version-min=10.15 -target x86_64-apple-ios13.0-macabi -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/ssl\"" -DENGINESDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DOPENSSL_API_COMPAT=0x10100000L  -MMD -MF crypto/aes/aes_core.d.tmp -MT crypto/aes/aes_core.o -c -o crypto/aes/aes_core.o crypto/aes/aes_core.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I. -Icrypto/include -Iinclude -fPIC -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk -fno-common -mmacosx-version-min=10.15 -target x86_64-apple-ios13.0-macabi -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/ssl\"" -DENGINESDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DOPENSSL_API_COMPAT=0x10100000L  -MMD -MF crypto/aes/aes_ecb.d.tmp -MT crypto/aes/aes_ecb.o -c -o crypto/aes/aes_ecb.o crypto/aes/aes_ecb.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I. -Icrypto/include -Iinclude -fPIC -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk -fno-common -mmacosx-version-min=10.15 -target x86_64-apple-ios13.0-macabi -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/ssl\"" -DENGINESDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DOPENSSL_API_COMPAT=0x10100000L  -MMD -MF crypto/aes/aes_ige.d.tmp -MT crypto/aes/aes_ige.o -c -o crypto/aes/aes_ige.o crypto/aes/aes_ige.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I. -Icrypto/include -Iinclude -fPIC -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk -fno-common -mmacosx-version-min=10.15 -target x86_64-apple-ios13.0-macabi -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/ssl\"" -DENGINESDIR="\"/Users/arvintan/OpenSSL-for-iPhone/bin/MacOSX10.15.4-x86_64.sdk/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DOPENSSL_API_COMPAT=0x10100000L  -MMD -MF crypto/aes/aes_misc.d.tmp -MT crypto/aes/aes_misc.o -c -o crypto/aes/aes_misc.o crypto/aes/aes_misc.c
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk' [-Wmissing-sysroot]
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk' [-Wmissing-sysroot]
clang: warning: overriding '-mmacosx-version-min=10.15' option with '--target=x86_64-apple-ios13.0-macabi' [-Woverriding-t-option]
clang: warning: overriding '-mmacosx-version-min=10.15' option with '--target=x86_64-apple-ios13.0-macabi' [-Woverriding-t-option]
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk' [-Wmissing-sysroot]
clang: warning: overriding '-mmacosx-version-min=10.15' option with '--target=x86_64-apple-ios13.0-macabi' [-Woverriding-t-option]
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk' [-Wmissing-sysroot]
clang: warning: overriding '-mmacosx-version-min=10.15' option with '--target=x86_64-apple-ios13.0-macabi' [-Woverriding-t-option]
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk' [-Wmissing-sysroot]
clang: warning: overriding '-mmacosx-version-min=10.15' option with '--target=x86_64-apple-ios13.0-macabi' [-Woverriding-t-option]
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk' [-Wmissing-sysroot]
clang: warning: overriding '-mmacosx-version-min=10.15' option with '--target=x86_64-apple-ios13.0-macabi' [-Woverriding-t-option]
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk' [-Wmissing-sysroot]
clang: warning: overriding '-mmacosx-version-min=10.15' option with '--target=x86_64-apple-ios13.0-macabi' [-Woverriding-t-option]
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk' [-Wmissing-sysroot]
clang: warning: overriding '-mmacosx-version-min=10.15' option with '--target=x86_64-apple-ios13.0-macabi' [-Woverriding-t-option]
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk' [-Wmissing-sysroot]
clang: warning: overriding '-mmacosx-version-min=10.15' option with '--target=x86_64-apple-ios13.0-macabi' [-Woverriding-t-option]
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk' [-Wmissing-sysroot]
clang: warning: overriding '-mmacosx-version-min=10.15' option with '--target=x86_64-apple-ios13.0-macabi' [-Woverriding-t-option]
apps/apps.c:18:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk' [-Wmissing-sysroot]
clang: warning: overriding '-mmacosx-version-min=10.15' option with '--target=x86_64-apple-ios13.0-macabi' [-Woverriding-t-option]
In file included from apps/app_rand.c:10:
In file included from apps/apps.h:13:
In file included from ./e_os.h:16:
In file included from include/openssl/e_os2.h:243:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include/inttypes.h:16:15: fatal error: 'inttypes.h' file not foundapps/bf_prefix.c:10:10: fatal error: 'stdio.h' file not found

#include <stdio.h>
         ^~~~~~~~~
#include_next <inttypes.h>
              ^~~~~~~~~~~~
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk' [-Wmissing-sysroot]
clang: warning: overriding '-mmacosx-version-min=10.15' option with '--target=x86_64-apple-ios13.0-macabi' [-Woverriding-t-option]
apps/s_cb.c:11:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
In file included from apps/opt.c:9:
In file included from apps/apps.h:13:
In file included from ./e_os.h:16:
In file included from include/openssl/e_os2.h:243:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include/inttypes.h:16:15: fatal error: 'inttypes.h' file not found
#include_next <inttypes.h>
              ^~~~~~~~~~~~
apps/s_socket.c:11:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
crypto/aes/aes_core.c:39:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
crypto/aes/aes_ecb.c:10:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
In file included from crypto/aes/aes_ige.c:10:
include/internal/cryptlib.h:13:11: fatal error: 'stdlib.h' file not found
# include <stdlib.h>
          ^~~~~~~~~~
1 error generated.
make[1]: *** [crypto/aes/aes_ecb.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from crypto/aes/aes_misc.c:12:
In file included from crypto/aes/aes_locl.h:13:
In file included from include/openssl/e_os2.h:243:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include/inttypes.h:16:15: fatal error: 'inttypes.h' file not found
#include_next <inttypes.h>
              ^~~~~~~~~~~~
1 error generated.
make[1]: *** [crypto/aes/aes_misc.o] Error 1
1 error generated.
make[1]: *** [crypto/aes/aes_core.o] Error 1
1 error generated.
make[1]: *** [crypto/aes/aes_ige.o] Error 1
1 error generated.
1 error generated.
1 error generated.
make[1]: *** [apps/bf_prefix.o] Error 1
make[1]: *** [apps/app_rand.o] Error 1
make[1]: *** [apps/opt.o] Error 1
1 error generated.
1 error generated.
make[1]: *** [apps/s_socket.o] Error 1
make[1]: *** [apps/s_cb.o] Error 1
1 error generated.
make[1]: *** [apps/apps.o] Error 1
make: *** [all] Error 2
Error 1
make[1]: *** [apps/opt.o] Error 1
1 error generated.
make[1]: *** [apps/s_socket.o] Error 1
1 error generated.
make[1]: *** [apps/s_cb.o] Error 1
1 error generated.
make[1]: *** [apps/apps.o] Error 1
make: *** [all] Error 2

**Comment by zeroimpl** [comment]
Root issue is this:

> clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.4.sdk' [-Wmissing-sysroot]

For some reason, there is not a MacOSX10.15.4.sdk symlink anymore, but there is a MacOSX10.15.sdk symlink.

You can workaround by overriding the SDK version number used :
`./build-libssl.sh --targets=mac-catalyst-x86_64 --macosx-sdk=10.15`

I'm guessing the following line in build-libssl.sh needs to be modified to fix this:
`MACOSX_SDKVERSION=$(xcrun -sdk macosx --show-sdk-version)`

**Comment by geeksia1** [comment]
I'm also facing same issue..

**Comment by thomasnordquist** [comment]
I can confirm @zeroimpl's solution

**Comment by x2on** [comment]
Fixed in #205
