### ISSUE TITLE
Support for M1?

### ISSUE THREAD

**Issue by augard** [x2on/OpenSSL-for-iPhone#196]
I tried to add configuration for simulator and build it with newer openssl version, but it failed at end in lipo on duplicate architecture.

```
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/lukas/Developer/Cogvio/OpenSSL-for-iPhone/bin/iPhoneSimulator14.3-arm64.sdk/lib/libssl.a and /Users/lukas/Developer/Cogvio/OpenSSL-for-iPhone/bin/iPhoneOS14.3-arm64.sdk/lib/libssl.a have the same architectures (arm64) and can't be in the same fat output file
```

```
    ## Apple iOS simulator (arm64)
    "ios-sim-cross-arm64" => {
        inherit_from     => [ "darwin64-arm64-cc", "ios-cross-base", asm("aarch64_asm") ],
        cflags           => add("-arch arm64"),
        bn_ops           => "SIXTY_FOUR_BIT_LONG RC4_CHAR",
        perlasm_scheme   => "ios64",
        sys_id           => "iOS",
    },
```

**Comment by tcherna** [comment]
Hmm. Just trying to understand how to do this as well, but I don't think you want to add "ios-sim-cross-arm64" at all. We'd need a target "mac-catalyst-arm64"

something  like:

    ## Catalyst (arm64)
    # Based on 10-main.conf: ios-cross
    "mac-catalyst-arm64" => {
        inherit_from     => [ "darwin-common", "mac-catalyst-base", asm("aarch64_asm")],
        cflags           => add("-arch arm64"),
        bn_ops           => "SIXTY_FOUR_BIT_LONG RC4_CHAR",
        perlasm_scheme   => "ios64",
        sys_id           => "MacOSX",
    },

**Comment by tcherna** [comment]
but I think to your original warning, it's the same reason why you can't link the catalyst x86 with the sim x86, you need to build a separate output library for catalyst that you link to for the macOS target.

**Comment by tcherna** [comment]
ugh, I just noticed there is already a pending PR for this #195

**Comment by abdhilabs** [comment]
how to add "ios-sim-cross-arm64"  @tcherna ?

**Comment by tcherna** [comment]
see 195.

**Comment by kleber-maia** [comment]
It took me a hot second to figure this out:

1. Add the changes introduced in this PR (if it hasn't been merged yet): https://github.com/x2on/OpenSSL-for-iPhone/pull/195
2. This will build the libraries targeting Catalyst for x86(64) and ARM62 as well: `./build-libssl.sh --targets="mac-catalyst-x86_64 mac-catalyst-arm64"`

**Comment by vgritsenko** [comment]
See https://github.com/x2on/OpenSSL-for-iPhone/pull/200. It puts together an XCFramework which can be used on everywhere - Simulators on Intel Macs, M1 Macs, Catalyst, and iOS devices.

**Comment by ellzu** [comment]
see opensslconf.h:15
delete TARGET_OS_EMBEDDED
>> #elif TARGET_OS_IOS && TARGET_CPU_ARM64

**Comment by x2on** [comment]
M1 Support is now available.
