### ISSUE TITLE
build failed for openssl 1.0.2k

### ISSUE THREAD

**Issue by zhangjgbupt** [x2on/OpenSSL-for-iPhone#197]
./build-libssl.sh --version=1.0.2k

Build options
  OpenSSL version: 1.0.2k
  Targets: ios-sim-cross-x86_64 ios64-cross-arm64 ios64-cross-arm64e tvos-sim-cross-x86_64 tvos64-cross-arm64
  iOS SDK: 13.2
  tvOS SDK: 13.2
  Number of make threads: 12
  Configure options:  no-deprecated
  Build location: /Users/zhangjiangang/Downloads/OpenSSL-for-iPhone-master

Using openssl-1.0.2k.tar.gz
Building openssl-1.0.2k for iPhoneSimulator 13.2 x86_64...
  Logfile: /Users/zhangjiangang/Downloads/OpenSSL-for-iPhone-master/bin/iPhoneSimulator13.2-x86_64.sdk/build-openssl-1.0.2k.log
  Configure...
Problem during Configure - Please check /Users/zhangjiangang/Downloads/OpenSSL-for-iPhone-master/bin/iPhoneSimulator13.2-x86_64.sdk/build-openssl-1.0.2k.log

**Comment by x2on** [comment]
For older version you need to use older version of the script. currently it only supports 1.1.*

**Comment by OneMHz** [comment]
Is there a particular commit or release that you would expect to work?
