### ISSUE TITLE
OpenSSL built and ready for iOS/macOS (repo)

### ISSUE THREAD

**Issue by blazorin** [x2on/OpenSSL-for-iPhone#208]
### I've made a [repository](https://github.com/blazorin/EssentialLibs) which contains OpenSSL and Boost built and ready for iOS and macOS architectures.

**Includes thread-safe libraries aswell!**

If possible, do not close this issue, just trying to help!

**Comment by minlite** [comment]
Sorry to bump this up, but using prebuilt openssl should be avoided strictly, as there is no way to be sure that it doesn't contain any malicious code.
