### ISSUE TITLE
Xcode 14 - watchOS arm64 support

### ISSUE THREAD

**Issue by anko37** [x2on/OpenSSL-for-iPhone#214]
Hello, in Xcode 14 a new architecture is showing up for the Apple Watch, there will be also a "arm64" device. I have problem to generate the XCFramework including the arm64 architecture for the Apple Watch. Is there something missing in your script? Best regards.

**Comment by x2on** [comment]
Xcode 14 is currently beta - so no support at the moment.

**Comment by anko37** [comment]
Xcode 14 has been released yesterday, it would be great if your scripts would also support the arm64 architecture for the Apple Watch.

**Comment by x2on** [comment]
OpenSSL doesn't support watchos-cross-arm64 currently.
