### ISSUE TITLE
Set minimum versions to minimum supported rather than recent

### ISSUE THREAD

**Issue by rnapier** [x2on/OpenSSL-for-iPhone#220]
The minimum versions are currently very recent. For example 15.0 for iOS. These should be the oldest that are [supported by Xcode](https://developer.apple.com/support/xcode/). iOS should likely be 11.0 (in my tests, this works fine w/ Simulator, even though Xcode claims not to support it; I have not dug into how this impacts iPadOS). The current build settings generate warnings when linking against apps that target versions earlier than 15.

Alternately (or perhaps in addition), these should be overridable by the caller (likely by allowing the caller to set it in the environment like CONFIG_OPTIONS).

**Comment by x2on** [comment]
You can easily change the setting `IOS_MIN_SDK_VERSION` in the `build-libssl.sh` for your needs.
I will always support "current version" - 1.
