### ISSUE TITLE
No such module 'OpenSSL'

### ISSUE THREAD

**Issue by quanguyen** [x2on/OpenSSL-for-iPhone#227]
Thanks for the great work!

I want to generate `OpenSSL.xcframework` for my XCode 14.3 project running on iPhone 16.4. I run these 2 commands:
1. ./build-libssl.sh --cleanup --ios-sdk=16.4 --targets=ios-cross-arm64
2. ./create-xcframework

After 2., `OpenSSL.xcframework` is created. However, after dragging and dropping to Frameworks folder in my XCode project, XCode still fails to build with error: "No such module 'OpenSSL'".

How should I fix this?

Best regards,

**Comment by x2on** [comment]
Why are you only building for ios-cross-arm64?

**Comment by Alittlefly** [comment]
I have the same problem. First, I built for ios-sim-cross-x86_64 ios-sim-cross-arm64 ios-cross-arm64 mac-catalyst-x86_64 mac-catalyst-arm64.  Then,  I used it in a swift demo project.  And then the fail presented.

**Comment by Alittlefly** [comment]
I have the same problem. First, I built for ios-sim-cross-x86_64 ios-sim-cross-arm64 ios-cross-arm64 mac-catalyst-x86_64 mac-catalyst-arm64.  Then,  I used it in a swift demo project.  And then the fail presented.
