### ISSUE TITLE
Suggestion: add a final step to create links libcrypto.a and libssl. in dirs per platform

### ISSUE THREAD

**Issue by tallinn1960** [x2on/OpenSSL-for-iPhone#228]
If one wants to use the produced libcrypto- and libssl-.. in another c project for iOS, which most often uses configure to create the necessary buildfiles and expects openssl libs to be named libcrypto and libssl, it would be nice to have symlinks libcrypto.a and libssl.a in a directory per platform, as configure allows for setting the lib and include directory for openssl.

**Comment by x2on** [comment]
Hi, please feel free to make a PR for this.
