### ISSUE TITLE
M1 create-xcframework.sh  error

### ISSUE THREAD

**Issue by yaoyue** [x2on/OpenSSL-for-iPhone#232]
Apple M1 machine execution script  `./create-xcframework.sh`  build error report

* Creating library for iOS
ld: in lib/libssl-iOS.a(bio_ssl.o), building for macOS, but linking in object file built for iOS, file 'lib/libssl-iOS.a' for architecture arm64
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: internal link edit command failed

**Comment by x2on** [comment]
What says the build log? What version of xcode and Mac OS have you installed?
