### ISSUE TITLE
隐私声明和签名

### ISSUE THREAD

**Issue by luoxiankang2** [x2on/OpenSSL-for-iPhone#249]
As per the [Upcoming third-party SDK requirements](https://developer.apple.com/support/third-party-SDK-requirements/) using OpenSSL in an App on the App Store will require a privacy manifest (cf. [Privacy manifest files](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files)) starting May 1st. Since the package comes with precompiled libraries a code signature may also be required. Is that something that you would consider providing?

**Comment by NasrullahKhan** [comment]
@luoxiankang2 my app is continuously reject from apple app store..

Please correct the following issues and upload a new binary to App Store Connect.

ITMS-91065: Missing signature - Your app includes “Frameworks/openssl.framework/openssl”, which includes BoringSSL / openssl_grpc, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. If a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a signature file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a signature. For details about verifying the code signature for a third-party SDK, visit: https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks.
