### ISSUE TITLE
curl download fails to handle 301 error

### ISSUE THREAD

**Issue by Chris1LDN** [x2on/OpenSSL-for-iPhone#251]
I've been trying to use your script but have been hitting a problem. The openssl archive would be downloaded as 0 bytes. After a while trying to debug it, I've realised that the remote host is returning HTTP 301 - Moved permanently.

After a bit more investigation, I discovered that passing the -L option to curl causes it to follow the redirect. I've attached a patch that fixes the issue for me. (I had to give it a ".txt" suffix as github refused ".patch" for some reason).

P.S. Thanks for the project, very useful.

[openssl-for-iphone-redirect.txt](https://github.com/user-attachments/files/16628288/openssl-for-iphone-redirect.txt)

**Comment by YuvarajIcon** [comment]
Just an FYI, the script already has CURL_OPTIONS variable to pass custom curl arguments. You can use this variable to pass -L to the script if you do not want to modify the build script yourself, or wait for the contributors to make changes :)

`CURL_OPTIONS="-L" ./build-libssl.sh`
