### ISSUE TITLE
Arm64 problem while configure

### ISSUE THREAD

**Issue by arik-so** [x2on/OpenSSL-for-iPhone#28]
I have the latest Xcode version, and when executing the build script, all architectures work fine, except for arm64. When I get to arm64, the shell prints:
Problem while make - Please check […]/OpenSSL-for-iPhone-master/bin/iPhoneOS7.1-arm64.sdk/build-openssl-1.0.1g.log

When looking at the log, these are the last lines:
/opt/local/bin/ranlib: /opt/local/bin/ranlib: cannot execute binary file
ar: internal ranlib command failed
make[1]: **\* [../libcrypto.a] Error 1
make: **\* [build_crypto] Error 1

I googled the issue, and found this page: http://lists.cs.uiuc.edu/pipermail/llvmbugs/2014-March/033328.html, which suggested I change the ranlib path. So I changed my /opt/local/bin/ranlib alias to the recommended path suggested on the page, '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib', add then all architectures stopped working. I filtered the generation to arm64, but it still didn't work for that one, and the error remained the same. So I reversed to the original ranlib alias, and the other architectures except for arm64 resumed working.

Still, I really need it to compile for arm64. Could you suggest any resolutions to the issue?

**Comment by vixentael** [comment]
Hello from 2015! :)

Thank you @isa56k for your tips. I tried lots of suggestions, but yours worked.

I have the same issue on Yosemite 10.10.5 with Xcode 7.1 and installed Command Line Tools. Cocoapods 0.39.0. No MacPorts.

I found that `ranlib` was linked to `libtool`.

```
~ ls -lamo /opt/local/bin/ranlib          
lrwxr-xr-x  1 root  7 Jan 30  2014 /opt/local/bin/ranlib -> libtool
```

I removed link and copied ranlib from `/usr/bin/ranlib`

```
~ sudo rm /opt/local/bin/ranlib
~ sudo cp /usr/bin/ranlib /opt/local/bin/ranlib
~ ls -lamo /opt/local/bin/ranlib          
-rwxr-xr-x+ 1 root  14160 Oct 27 16:21 /opt/local/bin/ranlib
~ which ranlib
/opt/local/bin/ranlib
```

Just in case, I read that there could be similar issues with `ar`. My ar was okay.
```
~ which ar    
/opt/local/bin/ar
~ ls -lamo /opt/local/bin/ar    
-r-xr-xr-x+ 1 root  32176 Jul  5  2013 /opt/local/bin/ar
```

**Comment by raybellis** [comment]
I found it was sufficient just to remove /opt/local/bin from my path.
