### ISSUE TITLE
Open SSL 1.0.2d and 1.0.1p will be released on July 9th 2015

### ISSUE THREAD

**Issue by ranjanappa** [x2on/OpenSSL-for-iPhone#52]
Hi Guys,

There is a new Open SSL release on July 9th. Can you please update the project to use the latest libraries

Regards
Rakesh

**Comment by x2on** [comment]
Hi @ranjanappa,

as soon the new version are available it will be also changed here.

Best,

Felix

**Comment by x2on** [comment]
New version is integrated.
