### ISSUE TITLE
Works with Xcode 6.4?

### ISSUE THREAD

**Issue by casevictor** [x2on/OpenSSL-for-iPhone#54]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file:     /Users/victorcase/workspace/Telegram-2.8/MtProtoKit/../../../Downloads/openssl.framework/openssl(ebcdic.o) has no symbols

**Comment by x2on** [comment]
When does this error happens? building the framework, building your app? Does the Demo work?

**Comment by x2on** [comment]
Checked it again on multiple xcode versions - runs fine on Xcode 6.3, Xcode 6.4, Xcode 7
