### ISSUE TITLE
iOS 9 and XCode 7

### ISSUE THREAD

**Issue by cjkindel** [x2on/OpenSSL-for-iPhone#55]
I know that both iOS 9 and XCode 7 are in beta, but do you have an estimate of when OpenSSL-for-iPhone will be updated? I have tried to current version, but not suprisingly XCode fails to find the OpenSSL header files.

**Comment by x2on** [comment]
I compiled the demo project with Xcode 7 and it runs fine on iOS 9.
So please check your project settings.
