### ISSUE TITLE
Support for bitcode?

### ISSUE THREAD

**Issue by benf1977** [x2on/OpenSSL-for-iPhone#56]
I'm finding that when I build this project and include in am Xcode 7 / iOS 9 project, I can't enable bitcode because OpenSSL was not compiled with bitcode enabled. I've been able to build the project with Xcode 7 beta, but I think OpenSSL itself is being built with GCC?

Thanks for this project!

**Comment by cyphers** [comment]
Bitcode and WatchOS support need to be added to the build script. Bitcode is "-fembed-bitcode" and WatchOS is a bunch of little changes, probably best as its own script actually.

**Comment by benf1977** [comment]
Thanks. Like this?

	sed -ie "s!^CFLAG=!CFLAG=-isysroot ${CROSS_TOP}/SDKs/${CROSS_SDK} -fembed-bitcode -miphoneos-version-min=7.0 !" "Makefile"

I'm guessing not, because I got this build error:

    ld: 'dhparam.o' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture i386

**Comment by cyphers** [comment]
Did you use xcode-select to select the xcode beta? If not, you're just using Xcode 6 which doesn't support Bitcode.

**Comment by benf1977** [comment]
I did select the beta, but I think I didn't have a clean environment. After cleaning my failure seems to be running make. It seems like it's happily compiling but then craps out on the make command:

    making all in tools...
    make[1]: Nothing to be done for `all'.

**Comment by x2on** [comment]
The master branch has now support for bitcode

**Comment by benf1977** [comment]
Is there a reason the min version for SDK 9.0 is iOS 8.0? I'd like to be able to support iOS 7+.

**Comment by x2on** [comment]
Hi @benf1977 ,

i thought bitcode option is only available iOS 8+, but will check that.

**Comment by grEvenX** [comment]
I'm using the latest Cocoapod (1.0.204.1) and I'm still getting the following error
```
ld: '/Volumes/MacintoshHD/code/myapp/Pods/OpenSSL/lib/libcrypto.a(asn1_lib.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Is this a regression or am I doing something wrong?
I'm using the latest official XCode release (Version 7.1.1).

**Comment by x2on** [comment]
I'm not sure what the CocoaPods Spec does (it's not mine).
With my script you have to use the `libcrypto_ tvOS.a` file instead of `libcrypto.a`

**Comment by grEvenX** [comment]
Sorry @x2on, I see I posted this in the wrong github project and mistaken this one to be the "official" Cocoapod repo. Judging  by this PR https://github.com/FredericJacobs/OpenSSL-Pod/pull/24 it doesn't seem like we'll be getting support for bitcode on the official repo any time soon :P
