### ISSUE TITLE
OpenSSL build failed if the script file is present in the source code directory or the directory inside the source code

### ISSUE THREAD

**Issue by adilimran123** [x2on/OpenSSL-for-iPhone#62]
Hi Felix Schulze

First all of all thanks for the amazing script for building openSSL for iphone. 
I have been facing an issue with that if I place the script inside the openssl source code directory the openssl script failed. I skipped some steps in scripts of downloading the source code then making the src folder to extract the source code and building from there. The script works fine if run it one level up from source code directory.
I am attaching the screenshot of the log fie showing error.

<img width="574" alt="build" src="https://cloud.githubusercontent.com/assets/7380445/9425661/9108c328-4931-11e5-8c74-d250d8d45af0.png">

**Comment by x2on** [comment]
Hi @adilimran123,

thats done by design, the script downloads the source and extract it to a subfolder. If you change this you also must change the path to the source in the script.

**Comment by adilimran123** [comment]
Hi Felix Schulze,
Thanks for your response. Yes I have changed the path to the source in the
script as well and it starts to build the for the first architecture on the
list too but then it gives the error as attached in the issue.
