### ISSUE TITLE
Can I use the libs in another Xcode project I created?

### ISSUE THREAD

**Issue by borischou** [x2on/OpenSSL-for-iPhone#71]
I copied the two lib files to my own project but cannot pass compiling.

**Comment by x2on** [comment]
Sure. Just drop the generated lib files into your project and setup the header search path.

**Comment by HamzaGhazouani** [comment]
Hi @x2on, when I run the script in the sample project everything works fine, but I get an error when I add the libs to my project and I setup the header.
Could you please add in the ReadMe how we can setup a new project with openSSL.
Thanks a lot
