### ISSUE TITLE
Stopping the build process without error

### ISSUE THREAD

**Issue by plenio** [x2on/OpenSSL-for-iPhone#75]
When I start the build process with
./build-libssl.sh
it suddenly stops and does not continue till the Done message. 
The lib library is empty. 
It used to work, but now it is not working anymore

This is my complete console output: 
Using openssl-1.0.2e.tar.gz
Building openssl-1.0.2e for iPhoneSimulator 9.1 i386
Please stand by...

Do you have any ideas?

**Comment by x2on** [comment]
Please run with verbose.
./build-libssl.sh verbose

Or check the log files in the bin folder.

**Comment by plenio** [comment]
Thanks for the prompt answer. I tried with a fresh download and there it seems to work. 
In Github desktop everything seems to be synched. Sorry, I am kind of new to this. 

By the way: I checked the bin folder and could not find any log messages there.

**Comment by x2on** [comment]
After running there are a log file for every architecture (in the sub folder) - good that it works now, so I'm closing this issue)

**Comment by plenio** [comment]
Thanks for your support
