### ISSUE TITLE
Can't build AppleTVSimulator9.1-x86_64.sdk

### ISSUE THREAD

**Issue by ivan-ushakov** [x2on/OpenSSL-for-iPhone#79]
Hello,

I'm using Xcode 7.2 (7C68) and can't build library because AppleTVSimulator9.1-x86_64.sdk build failed. I attached log file.
[build-openssl-1.0.2e.log.zip](https://github.com/x2on/OpenSSL-for-iPhone/files/69576/build-openssl-1.0.2e.log.zip)

**Comment by x2on** [comment]
Hi @ivan-ushakov,

i could not reproduce your issue. Please post more details.

Best
