### ISSUE TITLE
Deploy error : "Failed to load Info.plist from bundle at path ...", fixed with pull request

### ISSUE THREAD

**Issue by jasonlamkk** [x2on/OpenSSL-for-iPhone#81]
when deploying the application that contain openssl.framework, following error occurs : 

Dec 28 15:49:09 <<someuser>> com.apple.dt.Xcode[61626] <Error>: Error Domain=LaunchServicesError Code=0 "The operation couldn’t be completed. (LaunchServicesError error 0.)" UserInfo=0x7f9e29779800 {Error=PackageInspectionFailed, ErrorDescription=Failed to load Info.plist from bundle at path /Users/<<someuser>>/Library/Developer/CoreSimulator/Devices/3E6E4AF2-BC06-499D-9628-CD4726B076F8/data/Library/Caches/com.apple.mobile.installd.staging/temp.aoJgbR/extracted/Payload/<<someapp>>.app/Frameworks/openssl.framework}

already fixed by including Info.plist into the framework

pull request submitted

**Comment by x2on** [comment]
The PR is merged.
