### ISSUE TITLE
Build stops with error

### ISSUE THREAD

**Issue by torokzsolt** [x2on/OpenSSL-for-iPhone#86]
Hello!
I downloaded your branch, and try to build openssl to use it in my iOS application. After a while the build process stops, and in the log file I have something like this (the demo xcode project keep says I have to run the script first):

cp: openssl: No such file or directory
make[1]: *** [install] Error 1
make: *** [install_sw] Error 1

[build-openssl-1.0.2e.log.zip](https://github.com/x2on/OpenSSL-for-iPhone/files/86166/build-openssl-1.0.2e.log.zip)

I'm using xCode 7.2 (7C68). Do you have any idea what am I doing wrong? I attached the full log I get
Thanks for your help

**Comment by omochi** [comment]
@torokzsolt 
Your root error may be follow. (at line 1131 in your zip)

```
Undefined symbols for architecture i386:
```

Make install error comes from simply nothing of copy source.

I worry about those lines at 1129, 1130.

```
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/lib/libSystem.dylib, file was built for x86_64 which is not the architecture being linked (i386): /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/lib/libSystem.dylib
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/lib/darwin/libclang_rt.ios.a, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/lib/darwin/libclang_rt.ios.a (5 slices)
```

Please tell me output of follows.

```bash
$ lipo -info /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/lib/libSystem.dylib
$ lipo -info /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin/libclang_rt.ios.a
```

Just for information, my result is

```bash
[omochi@omochi-MB ~]$ lipo -info /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/lib/libSystem.dylib
Architectures in the fat file: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/lib/libSystem.dylib are: i386 x86_64 
[omochi@omochi-MB ~]$ lipo -info /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin/libclang_rt.ios.a
Architectures in the fat file: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin/libclang_rt.ios.a are: i386 armv7 armv7k armv7s x86_64 arm64 
```

**Comment by torokzsolt** [comment]
Thanks for your answear. The output of the commands you asked for is the following:

>$ lipo -info /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/lib/libSystem.dylib
>Non-fat file: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/lib/libSystem.dylib is architecture: x86_64
>$ lipo -info /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin/libclang_rt.ios.a
>Architectures in the fat file: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin/libclang_rt.ios.a are: armv7 armv7k armv7s x86_64 arm64

**Comment by omochi** [comment]
@torokzsolt 
Hmm... This is strange.
We need i386 binary for 32bit iPhone Simulator target.
Its not special to OpenSSL, its iOS development generic topic.

I have no confidence, but recommend you to reinstall Xcode.

Or another approach, you can specify build target architectures with my fork of this script.

https://github.com/omochi/OpenSSL-for-iPhone/tree/new/selectable-archs

Please clone mine and switch branch `new/selectable-archs`.
I excluded i386 and AppleTVs below example.

```bash
$ git clone https://github.com/omochi/OpenSSL-for-iPhone.git
$ cd OpenSSL-for-iPhone
$ git checkout new/selectable-archs
$ ARCHS="armv7 arm64 x86_64" ./build-libssl.sh
```

**Comment by torokzsolt** [comment]
@omochi 
Thank you very much for your help. Reinstalling Xcode solved the problem. Now I get the same output for the suggested commands, than you are, and the build process finishes successfully.
Thanks again, I'm really greatfull

**Comment by omochi** [comment]
@torokzsolt Its good. 😊
