### ISSUE TITLE
The example app will crash on loading view in iOS 8

### ISSUE THREAD

**Issue by Zingoer** [x2on/OpenSSL-for-iPhone#91]
Reproduce:
1. run the script to build the library
2. open the project and choose iOS 8.x simulator or connect to a real iOS 8.x device
3. Launch the App and it will crash immediately when try to display the viewController's view

Reason:
Setting values into the subviews like textField in the viewDidLoad will lead to the error "unexpectedly found nil while unwrapping an Optional value". This is because the textField is nil.

Possible Solution:
In AppDelegate, ViewController initialization doesn't use the nib.
I add a line of code:
`let viewController = ViewController(nibName: "ViewController", bundle: nil)`
will solve the problem

**Comment by x2on** [comment]
Could not be reproduced here. Please clean your project and delete the app from the simulator and try again.
