### ISSUE TITLE
New Building Scripts for OpenSSL FIPS Object Module for iOS >= 7

### ISSUE THREAD

**Issue by winstonhong** [x2on/OpenSSL-for-iPhone#92]
Hello x2on and team.

Thank you very much for your building script for compiling OpenSSL for iOS >= 7 Devices on Mac OS X El Capitan (Darwin Kernel Version 15.0.0) for iOS >=7 device.

I have built a general OpenSSL module successfully using build-libssl.sh. The built OpenSSL library works well for iOS 9 device.

However, I failed to build OpenSSL FIPS module for iOS >=7 using three different approaches.

(1) I failed to build OpenSSL FIPS module after adding FIPS option to build-libssl.sh.

(Method A) failed

Line 27
CONFIG_OPTIONS=""

with FIPS option

CONFIG_OPTIONS="fips"   

(Method B) also failed

Line 165
./Configure no-asm darwin64-x86_64-cc --openssldir="${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk" ${LOCAL_CONFIG_OPTIONS}

with FIPS option

./Configure no-asm darwin64-x86_64-cc fips --openssldir="${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk" ${LOCAL_CONFIG_OPTIONS}

Similar changes are also applied to Lines 167, 171, 173

https://github.com/x2on/OpenSSL-for-iPhone/blob/master/build-libssl.sh

(Method C) also failed

Line 24 

VERSION="1.0.2f"  

is modified to the source code of OpenSSL FIPS Object Module

VERSION="fips-2.0.11"  

(2) I failed to build OpenSSL FIPS module for iOS >= 7 using the old version of building script provided by the OpenSSL website.

http://openssl.com/fips/2.0/platforms/ios/

https://mta.openssl.org/pipermail/openssl-users/2016-February/002940.html

(3) I failed to build OpenSSL FIPS module for iOS >= 7 on using the new version of building script provided by the OpenSSL website.

http://openssl.com/testing/validation-2.0/platforms/ios-7.1/

https://mta.openssl.org/pipermail/openssl-users/2016-February/002955.html

I have used Beyond Compare 4 to check the difference between openssl-1.0.2f/config (or Configure) and openssl-fips-2.0.11/config (or Configure). I do NOT know how to modify the setenv-ios-11.sh to build OpenSSL FIPS module for iOS >=8 under the new Mac OS available from Apple website.

The source code for OpenSSL FIPS Object Module is

https://www.openssl.org/source/openssl-fips-2.0.11.tar.gz

The source code for general OpenSSL Object Module (used by https://github.com/x2on/OpenSSL-for-iPhone/blob/master/build-libssl.sh) is

https://www.openssl.org/source/openssl-1.0.2f.tar.gz

Could you please also develop the building scripts for compiling OpenSSL FIPS Object Module on  for iOS >= 7 device based on the following the old version script?  Thank you very much.

http://openssl.com/testing/validation-2.0/platforms/ios-7.1/setenv-ios-11.sh

Or 

Would you please shed some light on how to modify the above building script setenv-ios-11.sh on Mac OS X El Capitan (Darwin Kernel Version 15.0.0) for iOS >=8 device? Thank you very much.

With best regards,

Winston Hong

**Comment by x2on** [comment]
Sorry there are no plans for supporting the FIPS module from my side.
